services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=sqlite:///./test.db # Database connection string
    volumes:
      - ./backend:/app
      
  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: always