version: '3.4'

services:
  gurneyguide:
    image: gurneyguide
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
  react-app:
    build: .
    ports:
      - "3000:80" # Map Nginx port to local machine
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production   
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: